version: '3'

services:
  hack-bsuir-serv:
    container_name: hack-bsuir-serv
    build: ./
    depends_on:
      - mongodb
    networks:
      - network-backend

  mongodb:
    image: mongo:latest
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - network-backend

networks:
  network-backend:
    external: true